version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: acourse_api_gateway
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./nginx/acourse.gateway.conf:/etc/nginx/conf.d/default.conf

networks:
  default:
    driver: bridge